source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'dalli', '~>2.0.2'
gem 'eventmachine'
gem 'mysql2','~>0.5.2'
gem 'oauth', '~> 0.5.5'
gem 'sequel','~>4.0'
gem 'RubyInline','~>3.12.4'
gem 'sqlite3','~>1.3.11'
gem 'daemons'
gem 'gmp'

group :development do
  gem 'RocketAMF','~>0.2.1'
  gem 'rspec','~>2.11.0'
end
